[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "guesslet"
version = "1"
readme = "README.md"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = [
    "guesslet"
]